# Assignment 14

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database.sqlite")
df = pd.read_sql_query("SELECT * FROM salaries" , conn)
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

# 1. 
#### What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')

In [11]:
df = df[
    (df["JobTitle"] != "Not Provided") &
    (df["JobTitle"] != "Not provided")
]

df.groupby("JobTitle")["TotalPayBenefits"].mean()

JobTitle
ACCOUNT CLERK                                     44035.664337
ACCOUNTANT                                        47429.268000
ACCOUNTANT INTERN                                 29031.742917
ACPO,JuvP, Juv Prob (SFERS)                       80266.370000
ACUPUNCTURIST                                     67594.400000
                                                      ...
X-RAY LABORATORY AIDE                             52705.880385
X-Ray Laboratory Aide                             69521.123200
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    53632.870000
Youth Comm Advisor                                60118.550000
ZOO CURATOR                                       66686.560000
Name: TotalPayBenefits, Length: 2158, dtype: float64

# 2. 
#### Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000

In [3]:
df["OvertimePay"] = pd.to_numeric(df["OvertimePay"], errors="coerce")
df[df["OvertimePay"] > 50000][["JobTitle", "OvertimePay"]]

                                                JobTitle  OvertimePay
1                        CAPTAIN III (POLICE DEPARTMENT)    106088.18
2                   WIRE ROPE CABLE MAINTENANCE MECHANIC     56120.71
5                     BATTALION CHIEF, (FIRE DEPARTMENT)     89062.90
7                     BATTALION CHIEF, (FIRE DEPARTMENT)     86362.68
9       ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)     71344.88
...                                                  ...          ...
118287                                  Transit Operator     51625.42
118341                                  Transit Operator     52550.53
119449                          Track Maintenance Worker     50265.23
119606                         Diagnostic Imaging Tech I     74935.96
120203                           Parking Control Officer     54738.36

[2164 rows x 2 columns]

# 3.
#### What is the total number of unique employees? exclude ('Not Provided', 'Not provided')

In [4]:
df[
    (df["EmployeeName"] != "Not Provided") &
    (df["EmployeeName"] != "Not provided")
]["EmployeeName"].nunique()

110808

## 4. Show The Top 10 highest Paid Employees

In [8]:
df[["EmployeeName" , "TotalPay"]].sort_values(by= "TotalPay" , ascending=(False)).head(10)

                EmployeeName    TotalPay
0             NATHANIEL FORD  9999999.00
110530           David Shinn   471952.64
110531            Amy P Hart   390111.98
36158         Gary Altenberg   362844.66
36166          John Goldberg   350403.41
72926            Samson  Lai   347102.32
110535       Ellen G Moffatt   344187.46
110532  William J Coaker Jr.   339653.70
72924         Gregory P Suhr   339282.07
36162      Frederick Binkley   337204.86

# 5.
#### Show All Employees Ordered By Their TotalPay Benefits In Descending Order

In [10]:
df[["EmployeeName" , "TotalPayBenefits"]].sort_values(by= "TotalPayBenefits" , ascending=(False))

                EmployeeName  TotalPayBenefits
0             NATHANIEL FORD         567595.43
110530           David Shinn         510732.68
110531            Amy P Hart         479652.21
110532  William J Coaker Jr.         436224.36
72924         Gregory P Suhr         425815.28
...                      ...               ...
148633        David M Turner              0.00
110527      Timothy E Gibson             -2.73
110528        Mark E Laherty             -8.20
110529         David P Kucia            -33.89
148652             Joe Lopez           -618.13

[148653 rows x 2 columns]

# Assignment Complete