# Assignment 15

In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("factbook.db")
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)
df = pd.read_sql_query("SELECT * FROM facts", conn)
df

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,3.256434e+07,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3.029278e+06,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,3.954217e+07,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,8.558000e+04,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,1.962535e+07,2.78,38.78,11.49,0.46
...,...,...,...,...,...,...,...,...,...,...,...
256,257,zh,Atlantic Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,258,xo,Indian Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,zn,Pacific Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,oo,Southern Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,xx,World,NaN,NaN,NaN,7.256490e+09,1.08,18.60,7.80,NaN

# 1. 
### List all cities where the area is greater than 5000, along with their population.

In [3]:
q = '''
SELECT cities.name, cities.population
FROM cities
INNER JOIN facts
ON cities.facts_id = facts.id
WHERE facts.area > 5000
'''

df = pd.read_sql_query(q, conn)
df

          name  population
0    Abu Dhabi      942000
1        Dubai     1978000
2      Sharjah      983000
3        Kabul     3097000
4      Algiers     2916000
..         ...         ...
349    Mbabane       66000
350      Sanaa     2419000
351       Aden      784000
352     Lusaka     1802000
353     Harare     1542000

[354 rows x 2 columns]

# 2. 
#### List the names of capital cities where the death rate is greater than 2% and the birth rate is less than 20%

In [11]:
q = '''
SELECT cities.name, facts.death_rate, facts.birth_rate
FROM cities
INNER JOIN facts
ON cities.facts_id = facts.id
WHERE facts.death_rate > 2
AND facts.birth_rate < 20;
'''

df = pd.read_sql_query(q, conn)
df

                 name  death_rate  birth_rate
0          Oranjestad        8.18       12.56
1        Saint John'S        5.69       15.85
2                Baku        7.07       16.64
3              Tirana        6.58       12.92
4             Yerevan        9.34       13.61
..                ...         ...         ...
261          Haiphong        5.93       15.96
262           Da Nang        5.93       15.96
263  Charlotte Amalie        8.54       10.31
264          Windhoek       13.91       19.80
265          Mata-Utu        5.06       13.45

[266 rows x 3 columns]

# 3. 
#### List the cities with a population growth rate between 1% and 5%, sorted in descending order by population growth.

In [7]:
q = """
SELECT 
    c.name,
    f.population_growth
FROM cities AS c
INNER JOIN facts AS f
ON c.facts_id = f.id
WHERE f.population_growth BETWEEN 1 AND 5
ORDER BY f.population_growth DESC
"""

df = pd.read_sql_query(q, conn)
df

          name  population_growth
0         Juba               4.02
1     Lilongwe               3.32
2    Bujumbura               3.28
3       Niamey               3.25
4      Kampala               3.24
..         ...                ...
210        Fes               1.00
211  Marrakech               1.00
212    Tangier               1.00
213     Agadir               1.00
214    Managua               1.00

[215 rows x 2 columns]

# 4. 
#### Find countries that start with &quot;A&quot; and do not have any cities listed in the cities table. The query should return the country name and city name. Using left join

In [9]:
q = """
SELECT 
    f.name AS country_name,
    c.name AS city_name
FROM facts AS f
LEFT JOIN cities AS c
ON f.id = c.facts_id
WHERE f.name LIKE 'A%'
AND c.name IS NULL
"""

df = pd.read_sql_query(q, conn)
df

                  country_name city_name
0  Ashmore and Cartier Islands      None
1                     Akrotiri      None
2                   Antarctica      None
3                 Arctic Ocean      None
4               Atlantic Ocean      None

# 5. 
## List all capital cities and their corresponding death rate using a LEFT JOIN.

In [10]:
q = """
SELECT 
    c.name AS city_name,
    f.death_rate
FROM cities AS c
LEFT JOIN facts AS f
ON c.facts_id = f.id
WHERE c.capital = 1
"""

df = pd.read_sql_query(q, conn)
df

        city_name  death_rate
0      Oranjestad        8.18
1    Saint John'S        5.69
2       Abu Dhabi        1.97
3           Kabul       13.89
4         Algiers        4.31
..            ...         ...
203          Apia        5.32
204       Mbabane       13.56
205         Sanaa        6.28
206        Lusaka       12.67
207        Harare       10.13

[208 rows x 2 columns]

# Assignment 15 Completed!